### ISSUE TITLE
User Opinions are stored and exposed via API

### ISSUE THREAD

**Issue by imsickofmaps** [praekeltfoundation/go-nike-ghr#15]
This should be one row in a model with 6 columns (5 opinions and one updated_at column). Pre-populate with "".

```
{"opinions": 
    {
        "1": "Opinion one",
        "2": "Opinion two",
        "3": "Opinion three",
        "4": "Opinion four",
        "5": "Opinion five"
    }
}
```

**Comment by gitumarkk** [comment]
Was thinking that instead of `"1": "Opinion one"`, could be `"opinion_1": "Opinion one"` as it will prevent me trying to change the format the API spits out, or is the structure absolute? @imsickofmaps
