### ISSUE TITLE
current article exposed as json

### ISSUE THREAD

**Issue by imsickofmaps** [praekeltfoundation/go-nike-ghr#5]
Expose the article that is "published" and has a publish date of less than 7 days past in json format. No authentication is required.

Data should be literally as simple as:

```
{
    "article": "this is an article up to 480 chars long"
}
```

If no article is published return:

```
{
     "article": "Sorry there's no article this week, dial back soon!"
}
```

Ensure data is json encoded and returns correct content-type. See [here](http://stackoverflow.com/a/13011046/1549561) for details.

**Comment by gitumarkk** [comment]
:+1: will look into it
